### ISSUE TITLE
error triggered when switching between traits in user-supplied data

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_gis#10]
can share a test file that reproduces this, but just to get it into the system now; basically, it seems as though when you initially try to "Go" to a newly selected trait that was loaded from your user data file, the color updating is throwing an error which makes it appear to the user as though no results are present for their selected search. After seeing this state, if the view is zoomed or moved, the color update seems to work and the view appears as expected. The console error is below

angular.min.js:117 TypeError: Cannot read property 'length' of undefined
    at Object.test (chroma.min.js:32)
    at new a (chroma.min.js:32)
    at chroma.min.js:32
    at s (chroma.min.js:32)
    at r (chroma.min.js:32)
    at geoJson.js:714
    at arrayEach (lodash.js:451)
    at Function.forEach (lodash.js:8634)
    at colorStrategyNumericTrait (geoJson.js:697)
    at Object.s.updateColors (geoJson.js:876)

**Comment by guidorice** [comment]
thanks, will look into this.

**Comment by guidorice** [comment]
@adf-ncgr can you send me the data file and exact steps to reproduce? I am not seeing this exception so far in my testing. I am able to generate a different exception, however, when using the example data set:

```
angular.js:13920TypeError: Cannot read property '_isOpen' of undefined
    at map.js:388
    at eachLayer (leaflet.js:6)
    at updateMarkersAndPopups (map.js:380)
    at angular.js:19612
    at e (angular.js:5964)
    at angular.js:6243
```

**Comment by guidorice** [comment]
I was able to reproduce this with these steps.

- Menu button | add my data
- Load the dataset for Medicago in Mediterranean which adf sent
- the display will default to `nodA` for the trait view
- click Search button
- The Taxon field is empty at this point, which is a bug.
- Fill in Medicago truncatula in the Search Taxon field
- Select another custom trait, like GH2_flowerdate
- Click OK or Go
- Map displays the GH2_flowerdate, but the tabular listing says Results: 0 (bug)
- Zoom or scroll the map frame, and the Results is 250 accessions, as it should be.

**Comment by guidorice** [comment]
I believe I have fixed this with https://github.com/legumeinfo/lis_gis/commit/eace365fd35995fc884634be9f09955ae6d1fb0b
at least, I was unable to reproduce again today when testing.
