### ISSUE TITLE
errors encountered when searching for some germplasm accessions

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_gis#17]
AFAICT, this happens only in the instance backed by the new databases that @svengato populated and when looking for a germplasm accession that didn't exist in the older database (this is just how I've triggered the error in minimal testing, possibly those are not the necessary and sufficient conditions).

An example:
http://dev.lis.ncgr.org:50081/#?zoom=7&maxRecs=200&taxonQuery=&traitOverlay=&traitScale=global&country=&geocodedOnly&traitExcludeUnchar=false&limitToMapExtent&lat=35.80&lng=-105.25&mapHeight=102.75&baseMap=ESRI%20-%20NatGeo%20(default,%20reference%20map)&ne_lat=35.79999392988527&ne_lng=-97.613525390625&sw_lat=35.79999392988527&sw_lng=-112.88452148437501&accessionIdsInclusive=false&accessionIds=W6%2051204

My guess is that it is trying to do some sort of join to a table that hasn't been freshly populated, so this works fine for accessions that have been there all along (because they are grandfathered in with stale data in the joined table), but newly loaded accessions end up returning nothing due to an inner join not matching. This could be totally offbase, but is the only theory I could think of to explain the observed behavior.

**Comment by svengato** [comment]
Findings so far:

1. There are only two tables with an 'accenumb' (accession name) column:
  lis_germplasm.grin_accession (the one I repopulated)
  lis_germplasm.legumes_grin_evaluation_data (seems to list individual interesting plant specimens or attributes (?), often from the same accession, with only 73781 of 145549 accessions represented)

2. Evidence that it is not doing a join: if I give it an accenumb from the first table with no entries in the second table, or even a fictitious one like "Ftumsch", it "successfully" executes the search, returning 0 results.

3. The URL query looks like
http://dev.lis.ncgr.org:50081/search?v=1707851736479 (PI 353598, works)
http://dev.lis.ncgr.org:50081/search?v=1707851797522 (W6 51204, fails)
The v field is just a timestamp, the query information is contained in a POST. Looking into that now.

**Comment by svengato** [comment]
I repopulated the database using (0, 0) instead of ('', '') to represent unknown latitude and longitude, as in the default database. The problem was that it was unable to check whether accessions with unknown lat/long were in the bounding "rectangle".

Your example works now. There are even 80 more (new) accessions than before.

**Comment by svengato** [comment]
If we can get the data from the BrAPI endpoint, it would be worth repopulating the other table as well.
(lis_germplasm.legumes_grin_evaluation_data)

**Comment by svengato** [comment]
Of the 80 new accessions, 2 were in the old/default database. So there are now 7078 accessions unique to the new database (obtained from the BrAPI endpoint), and 924 unique to the old database.
